name: "Reticulum DEV"
version: "0.34.0-dev"
slug: "reticulum_dev"
description: "Run a Reticulum Network Stack node directly on Home Assistant."
startup: "application"
boot: "auto"
init: false

ingress: true
ingress_port: 8100
panel_icon: "mdi:radio-tower"
panel_title: "Reticulum DEV"

arch:
  - amd64
  - aarch64

map:
  - type: addon_config
    read_only: false

host_network: true
uart: true

hassio_api: true
hassio_role: default

options:
  auto_interface: false
  internet_bootstrap: true
  tcp_interface: false
  tcp_host: ""
  tcp_port: 4242
  rnode_interface: false
  rnode_port: ""
  rnode_frequency: 0
  rnode_bandwidth: 125000
  rnode_txpower: 0
  rnode_spreadingfactor: 8
  rnode_codingrate: 5
  transport: false
  loglevel: "info"

schema:
  auto_interface: "bool"
  internet_bootstrap: "bool"
  tcp_interface: "bool"
  tcp_host: "str?"
  tcp_port: "port"
  rnode_interface: "bool"
  rnode_port: "str?"
  rnode_frequency: "int(0,1000000000)"
  rnode_bandwidth: "int(7800,1625000)"
  rnode_txpower: "int(0,37)"
  rnode_spreadingfactor: "int(5,12)"
  rnode_codingrate: "int(5,8)"
  transport: "bool"
  loglevel: "list(error|warning|notice|info|verbose|debug|path|extreme)"
